// <auto-generated />
using System;
using AimPark.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AimPark.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260827143246_AddRfidSuspendedFrom")]
    partial class AddRfidSuspendedFrom
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AimPark.API.Entities.AdminAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TargetUserId");

                    b.ToTable("AdminAuditLogs");
                });

            modelBuilder.Entity("AimPark.API.Entities.AppealEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppealId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppealId");

                    b.ToTable("AppealEvidence");
                });

            modelBuilder.Entity("AimPark.API.Entities.DeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("LastSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Platform")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("DeviceTokens");
                });

            modelBuilder.Entity("AimPark.API.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sha256")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Sha256");

                    b.HasIndex("UserId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("AimPark.API.Entities.DocumentVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConfirmedLicenseExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConfirmedLicenseName")
                        .HasColumnType("text");

                    b.Property<string>("ConfirmedPlateNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ConfirmedRegistrationExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConfirmedSection")
                        .HasColumnType("text");

                    b.Property<string>("ConfirmedSemester")
                        .HasColumnType("text");

                    b.Property<string>("ConfirmedStudentName")
                        .HasColumnType("text");

                    b.Property<string>("ConfirmedStudentNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("EnrollmentValidity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExtractedLicenseExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtractedLicenseName")
                        .HasColumnType("text");

                    b.Property<string>("ExtractedPlateNumber")
                        .HasColumnType("text");

                    b.Property<string>("ExtractedPlatePhotoNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExtractedRegistrationExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtractedSection")
                        .HasColumnType("text");

                    b.Property<string>("ExtractedSemester")
                        .HasColumnType("text");

                    b.Property<string>("ExtractedStudentName")
                        .HasColumnType("text");

                    b.Property<string>("ExtractedStudentNumber")
                        .HasColumnType("text");

                    b.Property<string>("LicenseValidity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameMatch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("OverriddenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OverriddenByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlateMatch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlatePhotoMatch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawPayloads")
                        .HasColumnType("text");

                    b.Property<string>("RegistrationValidity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WasOverridden")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("DocumentVerifications");
                });

            modelBuilder.Entity("AimPark.API.Entities.GateDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApiKeyPrefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Gate")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyHash")
                        .IsUnique();

                    b.ToTable("GateDevices");
                });

            modelBuilder.Entity("AimPark.API.Entities.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<Guid>("ReportedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("ReportedByUserId");

                    b.HasIndex("Status");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("AimPark.API.Entities.IncidentEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.ToTable("IncidentEvidence");
                });

            modelBuilder.Entity("AimPark.API.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetRole")
                        .HasColumnType("text");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TargetUserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AimPark.API.Entities.NotificationRead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReadAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("NotificationId", "UserId")
                        .IsUnique();

                    b.ToTable("NotificationReads");
                });

            modelBuilder.Entity("AimPark.API.Entities.ParkingLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExitTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LoggedByDeviceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LoggedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SlotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EntryTime");

                    b.HasIndex("SlotId");

                    b.HasIndex("UserId");

                    b.ToTable("ParkingLogs");
                });

            modelBuilder.Entity("AimPark.API.Entities.ParkingRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("RatePerHour")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("VehicleType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("VehicleType")
                        .IsUnique()
                        .HasFilter("\"VehicleType\" IS NOT NULL");

                    b.ToTable("ParkingRates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000f1"),
                            RatePerHour = 15.00m,
                            UpdatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AimPark.API.Entities.ParkingSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Gate")
                        .HasColumnType("integer");

                    b.Property<string>("SlotCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("VehicleType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SlotCode")
                        .IsUnique();

                    b.HasIndex("Gate", "VehicleType", "Status");

                    b.ToTable("ParkingSlots");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gate = 1,
                            SlotCode = "G1-C1",
                            Status = "Available",
                            UpdatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleType = "Car"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gate = 1,
                            SlotCode = "G1-C2",
                            Status = "Available",
                            UpdatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleType = "Car"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gate = 1,
                            SlotCode = "G1-M1",
                            Status = "Available",
                            UpdatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleType = "Motorcycle"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gate = 1,
                            SlotCode = "G1-M2",
                            Status = "Available",
                            UpdatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleType = "Motorcycle"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gate = 1,
                            SlotCode = "G1-M3",
                            Status = "Available",
                            UpdatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleType = "Motorcycle"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gate = 1,
                            SlotCode = "G1-M4",
                            Status = "Available",
                            UpdatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleType = "Motorcycle"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gate = 1,
                            SlotCode = "G1-M5",
                            Status = "Available",
                            UpdatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleType = "Motorcycle"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gate = 1,
                            SlotCode = "G1-M6",
                            Status = "Available",
                            UpdatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleType = "Motorcycle"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gate = 1,
                            SlotCode = "G1-M7",
                            Status = "Available",
                            UpdatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleType = "Motorcycle"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gate = 1,
                            SlotCode = "G1-M8",
                            Status = "Available",
                            UpdatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleType = "Motorcycle"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gate = 2,
                            SlotCode = "G2-C1",
                            Status = "Available",
                            UpdatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleType = "Car"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gate = 2,
                            SlotCode = "G2-C2",
                            Status = "Available",
                            UpdatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleType = "Car"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            CreatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gate = 2,
                            SlotCode = "G2-M1",
                            Status = "Available",
                            UpdatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleType = "Motorcycle"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gate = 2,
                            SlotCode = "G2-M2",
                            Status = "Available",
                            UpdatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleType = "Motorcycle"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            CreatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gate = 2,
                            SlotCode = "G2-M3",
                            Status = "Available",
                            UpdatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleType = "Motorcycle"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            CreatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gate = 2,
                            SlotCode = "G2-M4",
                            Status = "Available",
                            UpdatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleType = "Motorcycle"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            CreatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gate = 2,
                            SlotCode = "G2-M5",
                            Status = "Available",
                            UpdatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleType = "Motorcycle"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            CreatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gate = 2,
                            SlotCode = "G2-M6",
                            Status = "Available",
                            UpdatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleType = "Motorcycle"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            CreatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gate = 2,
                            SlotCode = "G2-M7",
                            Status = "Available",
                            UpdatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleType = "Motorcycle"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            CreatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gate = 2,
                            SlotCode = "G2-M8",
                            Status = "Available",
                            UpdatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleType = "Motorcycle"
                        });
                });

            modelBuilder.Entity("AimPark.API.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountDue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParkingLogId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RatePerHourApplied")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ViolationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParkingLogId")
                        .IsUnique()
                        .HasFilter("\"ParkingLogId\" IS NOT NULL");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("ViolationId")
                        .IsUnique()
                        .HasFilter("\"ViolationId\" IS NOT NULL");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("AimPark.API.Entities.PolicyRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Parking");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("DefaultPenaltyAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("DefaultSuspensionDays")
                        .HasColumnType("integer");

                    b.Property<string>("DefaultSuspensionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("PolicyRules");
                });

            modelBuilder.Entity("AimPark.API.Entities.RegistrationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<string>("LastOtpChannel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OtpAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OtpExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OtpHash")
                        .HasColumnType("text");

                    b.Property<string>("PendingAuthProvider")
                        .HasColumnType("text");

                    b.Property<string>("PendingExternalProviderId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("RegistrationSessions");
                });

            modelBuilder.Entity("AimPark.API.Entities.SystemErrorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ErrorType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("TraceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("SystemErrorLogs");
                });

            modelBuilder.Entity("AimPark.API.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Affiliation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CanReapplyAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentRetakeJson")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EnrollmentValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalProviderId")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<int>("PasswordResetOtpAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PasswordResetOtpExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordResetOtpHash")
                        .HasColumnType("text");

                    b.Property<string>("RegistrationStep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RejectionCount")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("RfidStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RfidSuspendedFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RfidSuspendedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RfidTagId")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .HasColumnType("text");

                    b.Property<string>("StudentNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TermsAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RfidTagId")
                        .IsUnique()
                        .HasFilter("\"RfidTagId\" IS NOT NULL AND \"RfidTagId\" <> ''");

                    b.HasIndex("StudentNumber")
                        .IsUnique()
                        .HasFilter("\"StudentNumber\" IS NOT NULL AND \"StudentNumber\" <> ''");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AimPark.API.Entities.UserActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<string>("EmailAtTime")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("UserActivityLogs");
                });

            modelBuilder.Entity("AimPark.API.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RegistrationRenewalMonth")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RegistrationValidThrough")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlateNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("vehicles");
                });

            modelBuilder.Entity("AimPark.API.Entities.Violation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IssuedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParkingLogId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PenaltyAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("PolicyRuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SuspensionDays")
                        .HasColumnType("integer");

                    b.Property<string>("SuspensionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParkingLogId");

                    b.HasIndex("PolicyRuleId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Violations");
                });

            modelBuilder.Entity("AimPark.API.Entities.ViolationAppeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReasonText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ViolationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ViolationId")
                        .IsUnique();

                    b.ToTable("ViolationAppeals");
                });

            modelBuilder.Entity("AimPark.API.Entities.AppealEvidence", b =>
                {
                    b.HasOne("AimPark.API.Entities.ViolationAppeal", "Appeal")
                        .WithMany()
                        .HasForeignKey("AppealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appeal");
                });

            modelBuilder.Entity("AimPark.API.Entities.DeviceToken", b =>
                {
                    b.HasOne("AimPark.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AimPark.API.Entities.Document", b =>
                {
                    b.HasOne("AimPark.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AimPark.API.Entities.DocumentVerification", b =>
                {
                    b.HasOne("AimPark.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AimPark.API.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AimPark.API.Entities.Incident", b =>
                {
                    b.HasOne("AimPark.API.Entities.User", "ReportedByUser")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportedByUser");
                });

            modelBuilder.Entity("AimPark.API.Entities.IncidentEvidence", b =>
                {
                    b.HasOne("AimPark.API.Entities.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("AimPark.API.Entities.NotificationRead", b =>
                {
                    b.HasOne("AimPark.API.Entities.Notification", "Notification")
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AimPark.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AimPark.API.Entities.ParkingLog", b =>
                {
                    b.HasOne("AimPark.API.Entities.ParkingSlot", "Slot")
                        .WithMany()
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AimPark.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Slot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AimPark.API.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("AimPark.API.Entities.ParkingLog", "ParkingLog")
                        .WithMany()
                        .HasForeignKey("ParkingLogId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AimPark.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AimPark.API.Entities.Violation", "Violation")
                        .WithMany()
                        .HasForeignKey("ViolationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParkingLog");

                    b.Navigation("User");

                    b.Navigation("Violation");
                });

            modelBuilder.Entity("AimPark.API.Entities.Vehicle", b =>
                {
                    b.HasOne("AimPark.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AimPark.API.Entities.Violation", b =>
                {
                    b.HasOne("AimPark.API.Entities.ParkingLog", "ParkingLog")
                        .WithMany()
                        .HasForeignKey("ParkingLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AimPark.API.Entities.PolicyRule", "PolicyRule")
                        .WithMany()
                        .HasForeignKey("PolicyRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AimPark.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParkingLog");

                    b.Navigation("PolicyRule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AimPark.API.Entities.ViolationAppeal", b =>
                {
                    b.HasOne("AimPark.API.Entities.Violation", "Violation")
                        .WithMany()
                        .HasForeignKey("ViolationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Violation");
                });
#pragma warning restore 612, 618
        }
    }
}
